### ISSUE TITLE
dppm vs DPlatform

### ISSUE THREAD

**Issue by kn1g** [DFabric/dppm#2]
Hi, I just googled two days for the best private cloud solution for my AWS Server and ended up with the DPlatform. I read the deprecation message. So DPlatform is not maintained any more. Does dppm offer nextcloud and all the other services right now?

**Comment by j8r** [comment]
Hi @kn1g , thanks for your interest in the project!

DPlatform isn't totally kept unmaintained yet, but enter in a deprecated state.
The actual state is that dppm is missing features and applications. It is under active development to match and surpass DPlatform on this points.

The philosophy of both is to be separated of the operating system - you can't go wrong by still using DPlaftorm, specially if you are on Debian and want a one-shot working installation.

Right now, PHP applications aren't yet available on dppm, nor ARM architectures, but I'm working hard on it.
